### Send Email
POST https://pebjw1iuq0.execute-api.ap-northeast-2.amazonaws.com/contact/contact
Content-Type: application/json

{"email":"qudansdl@gmail.com","subject":"Sync 제휴 요청","message":"이름 :ㄹㄴㅇ\n전화번호 :01034208169\n회사 :ㄴㄹ\n내용 :ㄴㅇㄹㄴㅇㄹㄴㅇㄹㄴㅇ\n"}


### Send Email
{
  "email": "qudansdl@gmail.com",
  "subject": "subject",
  "message": "message"
}
